unit TestRawShapeBox2DConverter;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, uSoTypes, uRawShapes, uRawShapeBaseConverter,
  uGeometryClasses, UPhysics2D, uRawShapeBox2DConverter;

type
  // Test methods for class TRawShapeBox2DShapeConverter

  TestTRawShapeBox2DShapeConverter = class(TTestCase)
  strict private
    FRawShapeBox2DShapeConverter: TRawShapeBox2DShapeConverter;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConvertFrom;
    procedure TestConvertTo;
  end;

implementation

procedure TestTRawShapeBox2DShapeConverter.SetUp;
begin
  FRawShapeBox2DShapeConverter := TRawShapeBox2DShapeConverter.Create;
end;

procedure TestTRawShapeBox2DShapeConverter.TearDown;
begin
  FRawShapeBox2DShapeConverter.Free;
  FRawShapeBox2DShapeConverter := nil;
end;

procedure TestTRawShapeBox2DShapeConverter.TestConvertFrom;
var
  ReturnValue: TRawShape;
  AObject: Tb2Shape;
begin
  // TODO: Setup method call parameters
  ReturnValue := FRawShapeBox2DShapeConverter.ConvertFrom(AObject);
  // TODO: Validate method results
end;

procedure TestTRawShapeBox2DShapeConverter.TestConvertTo;
var
  ReturnValue: Tb2Shape;
  AShape: TRawShape;
begin
  // TODO: Setup method call parameters
  ReturnValue := FRawShapeBox2DShapeConverter.ConvertTo(AShape);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTRawShapeBox2DShapeConverter.Suite);
end.

